version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb_local"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

volumes:
  mongodb_data_container:
